### ISSUE TITLE
Clearer indication of software update progress/status

### ISSUE THREAD

**Issue by stevebow** [microsoft/XmlNotepad#104]
When carrying out a manual software update, the green “Up to date” message top right in the GUI is a little too subtle.  In fact, I did not notice this for a long time and thought the update process simply non functional during this time.

May I suggest instead a small status window open, informing the user that a check has been initiated along with the result of the check.  The window ought to have a cancel/close option during the check phase too.  Thanks.

**Comment by lovettchris** [comment]
I did add "Checking for updates..." to the status bar, in case that helps a little bit.  I'm actually not a huge fan of "modal dialogs" on long running operations.  Note also that checking for updates also happens automatically once per day and so technically you never need to really use that menu item.  And the fact that it could be running asynchronously in the background complicates your modal dialog idea since that would have to coordinate with any existing running operation etc...  It's simpler to keep the UI more background and hidden for now.  

How about a compromise, one thing people do to make a piece of UI more visible is to make it animate since movement catches the eye.

**Comment by stevebow** [comment]
The "Checking for updates..." in the status bar would help, if you prefer not to use a window.  I agree it needs more visibility if that's what you prefer.  I think if the background colour flashes on/off, for example, that would be fine.  For example, using XN just now, and I am sure I saw a green rectangle vanish top right, no idea what it was for as I hadn't noticed it.

Regarding auto updates, I loathe these and prefer programs not to phone home.  I didn't realize XN did this and have just disabled that in Options.  My suggestion for a modal dialog was based on the user initiating a manual check only, not the automatic checks which of course should occur in the background not interrupt the user.

**Comment by lovettchris** [comment]
Assuming this issue is resolved now.

**Comment by stevebow** [comment]
With Standalone 2.8.0.46, there a 2 problems I still see:

- If I disable my ethernet nic and run an update check via the Help menu, XN will report that it is up to date via the new green text box.  How can it be sure if it can't contact the update server?
- When running an update and it is reported in the green text box that XN is up to date, the text in the status bar right at the bottom of the XN window reports "Update Available".  Any further checks the text will become "Up to date".  The Status Bar will of course need to be enabled via the View menu to see this (for me it is always enabled by default whenever I start XN no matter if it is disabled when I quit XN).
