### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by JanuszCz** [microsoft/XmlNotepad#64]
It would be nice if it were possible to build it without problems. I've tried VS 2010, 1025, 2017m 2019 and I am getting all kinds of errors including obsolete and deprecated methods. Not possible to build from the get go.
Why open source then?

**Comment by lovettchris** [comment]
Can you try again with VS 2019? I just pushed a bunch of fixes in this area, thanks.

**Comment by lovettchris** [comment]
See also https://microsoft.github.io/XmlNotepad/#dev/

**Comment by JanuszCz** [comment]
Hi Chris,

 

Thank you for your response. Unfortunately, Outlook moved it to the spam folder, hence the delayed response.

I am still having problems building but this time there is something wrong with packages, that are missing. I need to check my settings. 

 

Regards,

Janusz (John) Z Czopowik

 

Amerpol®, Inc.

Computer Consulting

 

(256) 656-2312

**Comment by lovettchris** [comment]
It would help if you post the actual errors you are seeing.

**Comment by lovettchris** [comment]
Some build related issues were fixed recently, let me know if you still see problems, and post the actual errors, thanks.
